export const localizedContent = {
  'en-US': {
    bannerTitle: 'What would you like to eat?',
    recipes: 'Recipes',
    prepTime: 'Preparation time',
    cookTime: 'Cooking time',
    servings: 'Servings',
    ingredients: 'Ingredients',
    steps: 'Steps',
    level: 'Level',
    foodType: 'Food type',
    searchInput: 'Search...',
  },
  es: {
    bannerTitle: '¿Qué te apetece comer?',
    recipes: 'Recetas',
    prepTime: 'Tiempo de preparación',
    cookTime: 'Tiempo de cocción',
    servings: 'Comensales',
    ingredients: 'Ingredientes',
    steps: 'Pasos',
    level: 'Nivel',
    foodType: 'Tipo de comida',
    searchInput: 'Busca...',
  },
};
