export const localizedContent = {
  'en-US': {
    bannerTitle: 'What would you like to eat?',
    recipes: 'Recipes',
    prepTime: 'Preparation time',
    cookTime: 'Cooking time',
    servings: 'Servings',
    ingredients: 'Ingredients',
    steps: 'Steps',
    level: 'Level',
    foodType: 'Food type',
    searchInput: 'Search...',
    filters: 'Filters',
    vegan: 'Vegan',
    vegetarian: 'Vegetarian',
    drinks: 'Drinks',
    lunch: 'Lunch',
    breakfast: 'Breakfast',
    dessert: 'Dessert',
  },
  es: {
    bannerTitle: '¿Qué te apetece comer?',
    recipes: 'Recetas',
    prepTime: 'Tiempo de preparación',
    cookTime: 'Tiempo de cocción',
    servings: 'Comensales',
    ingredients: 'Ingredientes',
    steps: 'Pasos',
    level: 'Nivel',
    foodType: 'Tipo de comida',
    searchInput: 'Busca...',
    filters: 'Filtros',
    vegan: 'Vegano',
    vegetarian: 'Vegetariano',
    drinks: 'Bebidas',
    lunch: 'Comida',
    breakfast: 'Desayuno',
    dessert: 'Postre',
  },
};
