export const localizedContent = {
  'en-US': {
    bannerTitle: 'What would you like to eat?',
    recipes: 'Recipes',
    prepTime: 'Preparation time',
    cookTime: 'Cooking time',
    servings: 'Servings',
    ingredients: 'Ingredients',
    steps: 'Steps',
    level: 'Level',
    foodType: 'Food type',
    searchInput: 'Search...',
    filters: 'Filters',
    vegan: 'Vegan',
    vegetarian: 'Vegetarian',
    drinks: 'Drinks',
    meal: 'Meal',
    breakfast: 'Breakfast',
    dessert: 'Dessert',
    dinner: 'Dinner',
    category: 'Category',
    clear: 'Clear',
    dietType: 'Diet type',
    mealType: 'Meal type',
    goToDashboard: 'Go back to the dasboard',
    notFound: 'Page not found',
    recipesError: 'There was an error loading the recipes'
  },
  es: {
    bannerTitle: '¿Qué te apetece comer?',
    recipes: 'Recetas',
    prepTime: 'Tiempo de preparación',
    cookTime: 'Tiempo de cocción',
    servings: 'Comensales',
    ingredients: 'Ingredientes',
    steps: 'Pasos',
    level: 'Nivel',
    foodType: 'Tipo de comida',
    searchInput: 'Busca...',
    filters: 'Filtros',
    vegan: 'Vegano',
    vegetarian: 'Vegetariano',
    drinks: 'Bebidas',
    meal: 'Comida',
    breakfast: 'Desayuno',
    dessert: 'Postre',
    dinner: 'Cena',
    category: 'Categoría',
    clear: 'Borrar',
    dietType: 'Tipo de dieta',
    mealType: 'Tipo de comida',
    goToDashboard: 'Vuelve al panel inicial',
    notFound: 'Página no encontrada',
    recipesError: 'Ha habido un error cargando las recetas'
  },
};
